apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-demo
  namespace: gitops-demo

spec:
  replicas: 3

  selector:
    matchLabels:
      app: gitops-demo

  template:
    metadata:
      labels:
        app: gitops-demo

    spec:
      containers:
      - name: gitops-demo

        image: adityakhiroji/gitops-demo:60

        imagePullPolicy: Always

        ports:
        - containerPort: 80
